### ISSUE TITLE
LaTeX in the annotations

### ISSUE THREAD

**Issue by nkgsv** [dwhly-proj/droppdf#10]
Some LaTeX commands do not work in the annotations:

* `$a+b=c$` not rendered (but another option `\(a+b=c\)` works fine)

* `\(\mathbb R\)` does not work

* `\( \# \)` does not work

**Comment by dwhly** [comment]
Can you file this issue in https://github.com/hypothesis/client/issues  Thank you.

**Comment by nkgsv** [comment]
Filed [here](https://github.com/hypothesis/client/issues/165), thanks!
