### ISSUE TITLE
Fix share linking from an annotation

### ISSUE THREAD

**Issue by dwhly** [dwhly-proj/droppdf#34]
Share hyp.is link no longer takes user back to docdrop, but to YT. I assume this is because of the rel=canonical reference.  Should we *also* add a rel=canonical to the docdrop page *before* the YT reference?  Try an experiment. 

Paul said:

> it looks like the hyp.is share link picks up the second rel=canonical. If I put the “real” link before the youtube link it continues to pick up the youtube link, if I put it after it appears to pick up the page link (although I do get an error (The following error was encountered while trying to retrieve the URL: http://localhost:8000/video/QOrOYUxzX3o/) which I assume is probably from running a local server instead of a real domain?

Yes, let's change the order to "after" then.

**Comment by gabrielgrant** [comment]
My youtube annotations' share links seem to be working fine to load the dropdoc-ified version of a youtube video both with the extension installed and when loading in an incognito window (ie without the extension). Is there something I'm missing here, or is this fixed on the live site?

**Comment by genuineBuildMonkey** [comment]
This was completed so closing the issue.
