### ISSUE TITLE
Enable Google Analytics

### ISSUE THREAD

**Issue by dwhly** [dwhly-proj/droppdf#36]

**Comment by genuineBuildMonkey** [comment]
https://analytics.google.com/analytics/web/provision/?pli=1#/realtime/rt-overview/a181082912w250155043p231657731/

Dan was sent an invite from inside analytics control panel with full privileges.

Should anyone else be added?

**Comment by dwhly** [comment]
Paul— to which email was the invite directed?

D

+1 650 274 7647 m

**Comment by genuineBuildMonkey** [comment]
![image](https://user-images.githubusercontent.com/40497310/97369806-3e45ce80-1873-11eb-9572-c37af8dd9a2e.png)

**Comment by genuineBuildMonkey** [comment]
dwhaley@hypothes.is 

(should it be another email also?)

**Comment by dwhly** [comment]
Cool— I didn't understand how the interface worked when you were attached to multiple instances for multiple sites.

D

+1 650 274 7647 m

**Comment by genuineBuildMonkey** [comment]
Closing as done.
