### ISSUE TITLE
Upgrade PDFjs to recent version

### ISSUE THREAD

**Issue by dwhly** [dwhly-proj/droppdf#38]
Per @robertknight:

> I did look into this a while back but it was a bit of a pain in docdrop because there isn't a clean separation of PDF.js from the local modifications that have been made to it.  What would make this much easier is to create tools to update PDF.js in that project and then actually use them to update the copy in the repository. Example of how this was done for the h+PDF repo here: https://github.com/hypothesis/pdf.js-hypothes.is/pull/17

**Comment by genuineBuildMonkey** [comment]
Complete, in prod and working
